Style/Lambda:
  Enabled: false
Style/Next:
  Enabled: false
Style/IndentationConsistency:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
LineLength:
  Enabled: false
ClassLength:
  Enabled: false
AsciiComments:
  Enabled: false
Lint/Eval:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.1
